name: CI/CD
permissions:
  contents: read
  actions: read
  security-events: write
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build:
    name: Build & Test Django
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#============pip-audit (SCA)================
  sca-scan:
    name: pip-audit (SCA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run pip-audit (SCA)
        run: |
          pip install pip-audit
          pip install -r requirements.txt
          pip-audit --format json | python -m json.tool > pip-audit.json

      - name: Upload pip-audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: pip-audit.json
          retention-days: 5

#============Semgrep (SAST)================
  semgrep-scan:
    name: Semgrep (SAST)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep --config auto --sarif > semgrep.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

#============flake8 (linter)================
  linter:
    name: flake8 (Linter)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Run flake8
        run: |
          pip install flake8 flake8-json
          pip install -r requirements.txt
          flake8 . --ignore=E501 --statistics --count --exit-zero --format=json-pretty > flake8-report.json

      - name: Upload flake8 report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: flake8-report.json
          retention-days: 5

#============SOOS (DAST)=================
  SOOS-scan:
    name: SOOS (DAST)
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@a7eb40b94c1c81eb76b178ba1befdc21823f86fa
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "BSiAW_ToDoList_App"
          scan_mode: "baseline"
          target_url: "https://todoapp.pl"
          export_format: "Sarif"

      - name: Find and rename SARIF file
        run: |
          file=$(find . -name "*.sarif" | head -n 1)
          if [ -n "$file" ]; then
            mv "$file" soos.sarif
            echo "Renamed $file to soos.sarif"
          else
            echo "No SARIF file found" && exit 1
          fi
                    
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: soos.sarif
